name: Close Preview
run-name: "Close Preview #${{ github.event.number }}"

on:
  pull_request_target:
    types: [closed]

jobs:
  delete:
    name: Delete
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/book-preview
          ssh-key: ${{ secrets.PREVIEW_KEY }}
      - name: Commit and Push
        run: |
          git config user.name "Actions"
          git config user.email "action@github.com"
          git rm -r ${{ github.event.number }} || true
          git commit -m "Close Preview #${{ github.event.number }}" || true
          git push
