name: Deploy
run-name: Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Hugo
        run: sudo snap install hugo
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: hugo --minify
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
